# Generated by Django 4.2.7 on 2025-07-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # No dependencies needed as we are dropping tables from a removed app
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS chat_message;"),
        migrations.RunSQL("DROP TABLE IF EXISTS chat_room;"),
    ]
