# Generated by Django 5.0.7 on 2025-08-30 08:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_remove_chat_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for delivery option', max_length=100)),
                ('delivery_type', models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery'), ('overnight', 'Overnight Delivery'), ('free', 'Free Delivery')], default='standard', max_length=20)),
                ('charge', models.DecimalField(decimal_places=2, help_text='Delivery charge amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order value for this delivery option', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order value for this delivery option (leave blank for no limit)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_days', models.PositiveIntegerField(default=3, help_text='Estimated delivery days')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this delivery option is available')),
                ('is_default', models.BooleanField(default=False, help_text='Default delivery option')),
                ('description', models.TextField(blank=True, help_text='Additional description for delivery option')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Charge',
                'verbose_name_plural': 'Delivery Charges',
                'ordering': ['charge', 'estimated_days'],
            },
        ),
    ]
