# Generated by Django 5.2.4 on 2025-07-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100)),
                ('mineral_type', models.CharField(max_length=100)),
                ('operational_status', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='lease_media/')),
                ('is_video', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portfolio.lease')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='team_photos/')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='portfolio.lease')),
            ],
        ),
    ]
