# Generated by Django 4.2.7 on 2025-07-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_lease_operational_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='location',
            field=models.CharField(blank=True, choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=255),
        ),
        migrations.AlterField(
            model_name='lease',
            name='size',
            field=models.CharField(choices=[('Small (1-10 acres)', 'Small (1-10 acres)'), ('Medium (11-50 acres)', 'Medium (11-50 acres)'), ('Large (51-100 acres)', 'Large (51-100 acres)'), ('Extra Large (100+ acres)', 'Extra Large (100+ acres)')], default='Medium (11-50 acres)', max_length=100),
        ),
    ]
