# Generated by Django 4.2.7 on 2025-07-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_lease_location_alter_lease_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='mineral_type',
            field=models.CharField(choices=[('Coal', 'Coal'), ('Copper', 'Copper'), ('Gold', 'Gold'), ('Iron Ore', 'Iron Ore'), ('Limestone', 'Limestone'), ('Marble', 'Marble'), ('Salt', 'Salt'), ('Gypsum', 'Gypsum'), ('Chromite', 'Chromite'), ('Bauxite', 'Bauxite')], default='Coal', max_length=100),
        ),
    ]
