# Generated by Django 4.2.7 on 2025-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_lease_mineral_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
