# Generated by Django 4.2.7 on 2025-07-24 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_lease_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='role',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='lease',
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
        migrations.CreateModel(
            name='LeaseTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='portfolio.lease')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='portfolio.teammember')),
            ],
        ),
    ]
