# Generated by Django 4.2.7 on 2025-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='slug',
            field=models.SlugField(max_length=255, null=True, blank=True),
        ),
    ]
