# Generated by Django 4.2.7 on 2025-07-27 15:15

from django.db import migrations
from django.utils.text import slugify

def generate_lease_slugs(apps, schema_editor):
    Lease = apps.get_model('portfolio', 'Lease')
    for lease in Lease.objects.all():
        if not lease.slug:
            slug = slugify(lease.name)
            unique_slug = slug
            num = 1
            while Lease.objects.filter(slug=unique_slug).exists():
                unique_slug = f'{slug}-{num}'
                num += 1
            lease.slug = unique_slug
            lease.save()

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_lease_slug'),
    ]

    operations = [
        migrations.RunPython(generate_lease_slugs, reverse_code=migrations.RunPython.noop),
    ]
