# Generated by Django 4.2.7 on 2025-07-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_lease_slug'),
    ]

    operations = [
    ]
