# Generated by Django 4.2.7 on 2025-07-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20250727_1514'),
        ('portfolio', '0008_lease_slug_data_migration'),
    ]

    operations = [
    ]
