# Generated by Django 4.2.7 on 2025-07-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_lease_slug_alter_teammember_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='photo',
            new_name='profile_image',
        ),
    ]
