# Generated by Django 5.0.7 on 2025-08-30 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('cart', 'Cart Abandoned'), ('checkout', 'Checkout Abandoned')], default='cart', max_length=20)),
                ('cart_items_snapshot', models.JSONField()),
                ('cart_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_created_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField()),
                ('checkout_started_at', models.DateTimeField(blank=True, null=True)),
                ('cart_reminder_sent', models.BooleanField(default=False)),
                ('cart_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_reminder_sent', models.BooleanField(default=False)),
                ('checkout_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_recovered', models.BooleanField(default=False)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
