# Generated by Django 5.0.7 on 2025-08-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_abandonedcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_contact',
            field=models.CharField(blank=True, help_text='Courier contact number', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, help_text='Name of courier company', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number from courier', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='URL to track package online'),
        ),
    ]
