# Generated by Django 4.2.7 on 2025-07-27 09:46

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify

def forwards_func(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductCategory = apps.get_model('products', 'ProductCategory')
    db_alias = schema_editor.connection.alias

    for product in Product.objects.using(db_alias).all():
        category_name = getattr(product, 'category_old_text', None)
        if category_name:
            category_obj, created = ProductCategory.objects.using(db_alias).get_or_create(
                name=category_name,
                defaults={'slug': slugify(category_name)}
            )
            product.category = category_obj
            product.save()

def reverse_func(apps, schema_editor):
    # This function is not strictly necessary if you don't plan to reverse, but it's good practice.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams', max_digits=10, null=True),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_old_text',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='product',
            name='category_old_text',
        ),
    ]
