# Generated by Django 4.2.7 on 2025-07-27 10:10

from django.db import migrations
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if not product.slug:
            slug = slugify(product.name)
            unique_slug = slug
            num = 1
            while Product.objects.filter(slug=unique_slug).exists():
                unique_slug = f'{slug}-{num}'
                num += 1
            product.slug = unique_slug
            product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_product_price_product_sku_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_slugs, reverse_code=migrations.RunPython.noop),
    ]
