# Generated by Django 4.2.7 on 2025-07-27 10:25

from django.db import migrations

def generate_slugs(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        product.save() # This will use the updated save method to generate a unique slug

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250727_1510'),
    ]

    operations = [
        migrations.RunPython(generate_slugs, reverse_code=migrations.RunPython.noop),
    ]
