# Generated by Django 4.2.7 on 2025-07-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20250727_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mineral_type',
            field=models.CharField(choices=[('Coal', 'Coal'), ('Copper', 'Copper'), ('Gold', 'Gold'), ('Iron Ore', 'Iron Ore'), ('Limestone', 'Limestone'), ('Marble', 'Marble'), ('Salt', 'Salt'), ('Gypsum', 'Gypsum'), ('Chromite', 'Chromite'), ('Bauxite', 'Bauxite'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('tonne', 'tonnes'), ('carat', 'carats')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of the product', max_digits=10, null=True),
        ),
    ]
