# Generated by Django 4.2.7 on 2025-07-27 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_mineral_type_product_weight_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Must be a unique 8-12 digit number.', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_sku', message='SKU must be an 8 to 12 digit number.', regex='^[0-9]{8,12}$')]),
        ),
    ]
