# Generated by Django 4.2.7 on 2025-07-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_review_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
