# Generated by Django 5.0.7 on 2025-08-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mineral_type',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Product brand', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used - Like New'), ('vintage', 'Vintage'), ('antique', 'Antique'), ('refurbished', 'Refurbished')], default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_country',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing & Fashion'), ('Home & Garden', 'Home & Garden'), ('Books', 'Books & Media'), ('Sports', 'Sports & Outdoors'), ('Beauty', 'Beauty & Personal Care'), ('Toys', 'Toys & Games'), ('Jewelry', 'Jewelry & Accessories'), ('Art', 'Art & Collectibles'), ('Antiques', 'Antiques & Vintage'), ('Handmade', 'Handmade & Crafts'), ('Other', 'Other')], default='Other', help_text='Type of imported product', max_length=100),
        ),
    ]
