# Generated by Django 5.0.7 on 2025-08-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_mineral_type_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g., 18.00 for 18%)', max_digits=5),
        ),
    ]
