# Generated by Django 5.0.7 on 2025-08-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_tax_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PASHMINA', 'Pashmina'), ('CASHMERE', 'Cashmere'), ('WOOL', 'Wool'), ('SILK', 'Silk'), ('COTTON', 'Cotton'), ('BLEND', 'Blend'), ('OTHER', 'Other')], default='OTHER', help_text='Type of shawl material', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('oz', 'ounces')], default='kg', max_length=10),
        ),
    ]
